### ISSUE TITLE
Fix OJ

### ISSUE THREAD

**Issue by swalkinshaw** [thuva/json_serialization_benchmark#3]
Doesn't look like OJ is being used properly since by default it doesn't override `to_json`.

https://github.com/ohler55/oj#rails and http://techblog.thescore.com/benchmarking-json-generation-in-ruby/#comment-1401619547

**Comment by mrinterweb** [comment]
The pull request I just made https://github.com/thuva/json_serialization_benchmark/pull/4 should fix this.

**Comment by thuva** [comment]
I have PR https://github.com/thuva/json_serialization_benchmark/pull/5 based on the one by @mrinterweb that fixes this issue.

**Comment by thuva** [comment]
Fixed by https://github.com/thuva/json_serialization_benchmark/pull/5
